import Link from "next/link";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { getSiteConfig } from "@/lib/config";
import { PrivacyPolicyVideo } from "@/components/PrivacyPolicyVideo";

export const metadata: Metadata = {
  title: "Privacy Policy",
};

// Bumped only when the policy text below actually changes.
const LAST_UPDATED = "September 29, 2026";

export default function PrivacyPolicyPage() {
  const config = getSiteConfig();

  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col gap-8 px-6 py-16">
      <h1 className="text-center font-heading text-4xl font-extrabold uppercase text-text">
        Privacy Policy
      </h1>

      <div className="surface-panel overflow-hidden rounded-lg">
        <div className="relative aspect-video w-full">
          <PrivacyPolicyVideo />
        </div>
      </div>

      <article className="surface-panel flex flex-col gap-6 rounded-lg p-6 text-text sm:p-8">
        <p className="text-sm text-muted">Last updated: {LAST_UPDATED}</p>

        <p>
          {config.event.name} is a private, invite-only Halloween party. This site exists solely
          so invited guests can RSVP and check in, vote in the costume contest, and upload costume
          photos. It is not a public service, it is not open to anyone outside the guest list, and
          this policy is written with that in mind — it describes exactly what we do with your
          information for this one event, nothing more.
        </p>

        <Section title="What information we collect">
          <ul className="flex flex-col gap-2">
            <li>
              <strong className="text-text">Your name</strong> — first and last, as given at RSVP
              or walk-in registration.
            </li>
            <li>
              <strong className="text-text">Adult or minor status</strong> — a costume-category
              grouping (adult male, adult female, boy, or girl) used only to sort entries into the
              right costume-contest categories.
            </li>
            <li>
              <strong className="text-text">A costume photo</strong>, if you choose to upload one,
              shown during voting and in the results.
            </li>
            <li>
              <strong className="text-text">The votes you cast</strong> in the costume contest.
            </li>
            <li>
              <strong className="text-text">A passkey credential</strong>, if passkey sign-in is
              enabled for this event: a cryptographic public key generated by your own device
              (e.g. your phone&rsquo;s Face ID or fingerprint sensor) so you can sign back in
              without re-verifying every time.{" "}
              <strong className="text-text">
                We never receive, see, or store your fingerprint, face scan, or any other
                biometric data
              </strong>{" "}
              — only the public key your device uses to prove it&rsquo;s you. Your biometric data
              never leaves your own device.
            </li>
            <li>
              <strong className="text-text">A one-time phone verification code</strong>, if phone
              verification is used instead of a passkey: sent via SMS through Twilio to confirm
              it&rsquo;s really you. We don&rsquo;t keep a record of the phone number used to
              verify.
            </li>
          </ul>
        </Section>

        <Section title="Why we collect it">
          <p>
            Strictly to run the event: checking you in on arrival, running the costume contest
            (displaying photos for voting and tallying who voted for whom so winners can be
            determined), and letting you pick up where you left off on the same device without
            re-verifying every time.
          </p>
        </Section>

        <Section title="Who can see it">
          <p>
            Only the event hosts, George and Sarah, through a password-protected admin panel. No
            one else — not other guests, not advertisers, not the general public — has access to
            your name, photo, votes, or verification details.
          </p>
        </Section>

        <Section title="We don't sell or share your data">
          <p>
            Your information is never sold, rented, or shared with advertisers or any third party
            for marketing purposes. It is used exclusively to run this one private event, full
            stop.
          </p>
        </Section>

        <Section title="Service providers we use">
          <p>
            A few outside services help run this site, and each only processes your data on our
            behalf to do that — none of them are permitted to use it for their own purposes:
            Google Sheets/Drive (storing guest information and costume photos) and, when phone
            verification is used, Twilio (sending the one-time SMS code).
          </p>
        </Section>

        <Section title="How long we keep it">
          <p>
            Your information is kept only for the event and a reasonable period afterward — long
            enough to display final costume-contest results — and is deleted once it&rsquo;s no
            longer needed for those purposes.
          </p>
        </Section>

        <Section title="Your choices">
          <p>
            Uploading a costume photo is always optional — you can skip it. If a passkey ever
            doesn&rsquo;t work on your device, an admin can cast your vote for you in person at
            the event instead.
          </p>
        </Section>

        <Section title="Questions?">
          <p>
            If you have any questions about your information or this policy, contact us at{" "}
            <a href={`mailto:${config.event.contactEmail}`} className="text-primary underline">
              {config.event.contactEmail}
            </a>
            .
          </p>
        </Section>
      </article>

      <Link href="/" className="text-center text-sm text-muted underline hover:text-text">
        ← Back to home
      </Link>
    </main>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="font-heading text-lg font-bold uppercase text-primary">{title}</h2>
      {children}
    </section>
  );
}
